server: 
  port: 8070

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka

spring:
  zipkin:
    baseUrl: http://zipkin:9411
    
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: datadog

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
