eureka:
  client:
    serviceUrl:
      defaultZone: "http://discovery-service:8061/eureka"

server:
  port: 8060

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [trace_id: %X{traceId:-}, span_id: %X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    
spring:
  zipkin:
    baseUrl: http://zipkin:9411

management:
  tracing:
    sampling:
      probablity: 1.0
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
