eureka:
  client:
    serviceUrl:
      defaultZone: "http://discovery-service:8061/eureka"

server:
  port: 8060
    
spring:
  zipkin:
    baseUrl: http://zipkin:9411

management:
  tracing:
    sampling:
      probablity: 1.0
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
