eureka:
  client:
    serviceUrl:
      defaultZone: "http://discovery-service:8061/eureka"

server:
  port: 8080

spring:
  zipkin:
    baseUrl: http://zipkin:9411
    
management:
  tracing:
    sampling:
      probabilty: 1.0
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
